# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/kube-openapi/cmd/openapi-gen",
  "k8s.io/gengo/args",
  "sigs.k8s.io/controller-tools/pkg/crd/generator",
  "golang.org/x/sync/errgroup",
  "github.com/gobuffalo/packr/v2/file/resolver",
]

[[constraint]]
  name = "github.com/go-openapi/spec"
  version = "0.18.0"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "2.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.3.0"

[prune]
  go-tests = true
